### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by roger-** [getumbrel/llama-gpt#4]
I get the following after running docker compose (7b):

```
llama-gpt-llama-gpt-api-1  | Processing dependencies for llama-cpp-python==0.1.77
llama-gpt-llama-gpt-api-1  | Searching for diskcache==5.6.1
llama-gpt-llama-gpt-api-1  | Best match: diskcache 5.6.1
llama-gpt-llama-gpt-api-1  | Processing diskcache-5.6.1-py3.11.egg
llama-gpt-llama-gpt-api-1  | Adding diskcache 5.6.1 to easy-install.pth file
llama-gpt-llama-gpt-api-1  |
llama-gpt-llama-gpt-api-1  | Using /usr/local/lib/python3.11/site-packages/diskcache-5.6.1-py3.11.egg
llama-gpt-llama-gpt-api-1  |
llama-gpt-llama-gpt-api-1  | Searching for numpy==1.25.1
llama-gpt-llama-gpt-api-1  | Best match: numpy 1.25.1
llama-gpt-llama-gpt-api-1  | Processing numpy-1.25.1-py3.11-linux-x86_64.egg
llama-gpt-llama-gpt-api-1  | Adding numpy 1.25.1 to easy-install.pth file
llama-gpt-llama-gpt-api-1  | Installing f2py script to /usr/local/bin
llama-gpt-llama-gpt-api-1  | Installing f2py3 script to /usr/local/bin
llama-gpt-llama-gpt-api-1  | Installing f2py3.11 script to /usr/local/bin
llama-gpt-llama-gpt-api-1  |
llama-gpt-llama-gpt-api-1  | Using /usr/local/lib/python3.11/site-packages/numpy-1.25.1-py3.11-linux-x86_64.egg
llama-gpt-llama-gpt-api-1  |
llama-gpt-llama-gpt-api-1  | Searching for typing-extensions==4.7.1
llama-gpt-llama-gpt-api-1  | Best match: typing-extensions 4.7.1
llama-gpt-llama-gpt-api-1  | Adding typing-extensions 4.7.1 to easy-install.pth file
llama-gpt-llama-gpt-api-1  |
llama-gpt-llama-gpt-api-1  | Using /usr/local/lib/python3.11/site-packages
llama-gpt-llama-gpt-api-1  |
llama-gpt-llama-gpt-api-1  | Finished processing dependencies for llama-cpp-python==0.1.77
llama-gpt-llama-gpt-api-1  | Initializing server with:
llama-gpt-llama-gpt-api-1  | Batch size: 2096
llama-gpt-llama-gpt-api-1  | Number of CPU threads: 4
llama-gpt-llama-gpt-api-1  | Number of GPU layers: 0
llama-gpt-llama-gpt-api-1  | Context window: 4096
llama-gpt-llama-gpt-api-1  | Traceback (most recent call last):
llama-gpt-llama-gpt-api-1  |   File "/app/llama_cpp/llama_cpp.py", line 67, in _load_shared_library
llama-gpt-llama-gpt-api-1  |     return ctypes.CDLL(str(_lib_path), **cdll_args)
llama-gpt-llama-gpt-api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llama-gpt-llama-gpt-api-1  |   File "/usr/local/lib/python3.11/ctypes/__init__.py", line 376, in __init__
llama-gpt-llama-gpt-api-1  |     self._handle = _dlopen(self._name, mode)
llama-gpt-llama-gpt-api-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
llama-gpt-llama-gpt-api-1  | OSError: /app/llama_cpp/libllama.so: file too short
llama-gpt-llama-gpt-api-1  |
llama-gpt-llama-gpt-api-1  | During handling of the above exception, another exception occurred:
llama-gpt-llama-gpt-api-1  |
llama-gpt-llama-gpt-api-1  | Traceback (most recent call last):
llama-gpt-llama-gpt-api-1  |
llama-gpt-llama-gpt-api-1  |   File "<frozen runpy>", line 189, in _run_module_as_main
llama-gpt-llama-gpt-api-1  |   File "<frozen runpy>", line 112, in _get_module_details
llama-gpt-llama-gpt-api-1  |   File "/app/llama_cpp/__init__.py", line 1, in <module>
llama-gpt-llama-gpt-api-1  |     from .llama_cpp import *
llama-gpt-llama-gpt-api-1  |   File "/app/llama_cpp/llama_cpp.py", line 80, in <module>
llama-gpt-llama-gpt-api-1  |     _lib = _load_shared_library(_lib_base_name)
llama-gpt-llama-gpt-api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llama-gpt-llama-gpt-api-1  |   File "/app/llama_cpp/llama_cpp.py", line 69, in _load_shared_library
llama-gpt-llama-gpt-api-1  |     raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
llama-gpt-llama-gpt-api-1  | RuntimeError: Failed to load shared library '/app/llama_cpp/libllama.so': /app/llama_cpp/libllama.so: file too short
llama-gpt-llama-gpt-ui-1   | [INFO  wait] Host [llama-gpt-api:8000] not yet available...
llama-gpt-llama-gpt-api-1 exited with code 1
llama-gpt-llama-gpt-ui-1   | [INFO  wait] Host [llama-gpt-api:8000] not yet available...
llama-gpt-llama-gpt-ui-1   | [INFO  wait] Host [llama-gpt-api:8000] not yet available...
llama-gpt-llama-gpt-ui-1   | [INFO  wait] Host [llama-gpt-api:8000] not yet available...
llama-gpt-llama-gpt-ui-1   | [INFO  wait] Host [llama-gpt-api:8000] not yet available...
llama-gpt-llama-gpt-ui-1   | [INFO  wait] Host [llama-gpt-api:8000] not yet available...
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
```

**Comment by mayankchhabra** [comment]
@roger- Can you please share more details about your system including the architecture (x86 or arm64), OS, CPU, and RAM?

**Comment by roger-** [comment]
Sure:

* Linux nuc 5.4.0-156-generic #173-Ubuntu SMP Tue Jul 11 07:25:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Ubuntu 20.04.6 LTS
* 16 GB RAM

**Comment by Quarky93** [comment]
I'm getting the same issue on 13b and 70b models.
OS: Ubuntu 22.04.3
CPU: Epyc 9654 - 96 cores
RAM: 768 GB

```
Using /usr/local/lib/python3.11/site-packages
Finished processing dependencies for llama-cpp-python==0.1.77
Initializing server with:
Batch size: 2096
Number of CPU threads: 192
Number of GPU layers: 0
Context window: 4096
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:126: UserWarning: Field "model_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ('settings_',)`.
  warnings.warn(
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/llama_cpp/server/__main__.py", line 46, in <module>
    app = create_app(settings=settings)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/llama_cpp/server/app.py", line 313, in create_app
    llama = llama_cpp.Llama(
            ^^^^^^^^^^^^^^^^
  File "/app/llama_cpp/llama.py", line 308, in __init__
    raise ValueError(f"Model path does not exist: {model_path}")
ValueError: Model path does not exist: /models/llama-2-13b-chat.bin
Exception ignored in: <function Llama.__del__ at 0x7f10ea656ca0>
Traceback (most recent call last):
  File "/app/llama_cpp/llama.py", line 1507, in __del__
    if self.model is not None:
       ^^^^^^^^^^
AttributeError: 'Llama' object has no attribute 'model'
```

**Comment by matusnovak** [comment]
I am also having a very similar crashes with the 70b model:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/llama_cpp/server/__main__.py", line 46, in <module>
    app = create_app(settings=settings)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/llama_cpp/server/app.py", line 313, in create_app
    llama = llama_cpp.Llama(
            ^^^^^^^^^^^^^^^^
  File "/app/llama_cpp/llama.py", line 313, in __init__
    assert self.model is not None
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Exception ignored in: <function Llama.__del__ at 0x7fa4fb76aca0>
```

Full log here:
[llama-gpt-llama-gpt-api-1.log](https://github.com/getumbrel/llama-gpt/files/12363680/llama-gpt-llama-gpt-api-1.log)

Using the latest master branch commit: `c76225a6fc26a000fc07b074223a69b0d65b7bcf`

I have started it as:
```
docker compose -f docker-compose-70b.yml up -d
```

Specs:
OS: 6.2.16-2-MANJARO
CPU: AMD Threadripper 3970X
RAM: 128GB

**Comment by matusnovak** [comment]
I think I found a fix for my issue:
```
  File "/app/llama_cpp/llama.py", line 313, in __init__
    assert self.model is not None
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

The error:
```
llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  8192
```

Seems to point to the: https://github.com/facebookresearch/llama/issues/407

And some suggest to set `-gqa 8` to fix that issue. But I have no idea whether it is a proper fix since I have no idea about AI and the language models as a whole.

However based on the https://github.com/abetlen/llama-cpp-python/issues/528 you can't set it on the command line (i.e. modifying `run.sh` in this repo won't work). Instead, you need to add it as an environment variable.

Adding this:

```patch
diff --git a/docker-compose-70b.yml b/docker-compose-70b.yml
index c4c433b..a5b9d5a 100644
--- a/docker-compose-70b.yml
+++ b/docker-compose-70b.yml
@@ -8,6 +8,7 @@ services:
       dockerfile: 70B.Dockerfile
     environment:
       MODEL: '/models/llama-2-70b-chat.bin'
+      N_GQA: '8'
 
   llama-gpt-ui:
     image: 'ghcr.io/getumbrel/llama-gpt-ui:latest'
```

did solve my issue and I no longer got the error, both containers  started successfully.

**Comment by crackmac** [comment]
This worked for me too! Takes a while for the ui container to start, but it did after a few minutes.
You can drop the '-d' from 'docker-compose up' and watch the logs.

`docker compose -f docker-compose-70b.yml up`

**Comment by mayankchhabra** [comment]
Excellent! Thanks so much for investigating it and for the sharing the GQA requirement for 70B. We've pushed the changes to 70B's docker-compose.yml 2a24cb9e600ead49e2ef616d7f785eaf0613dc0b.

@roger- @Quarky93 feel free to try again now, and if it doesn't work, happy to reopen the issue.

**Comment by roger-** [comment]
Sorry I don't think that fix applies in my case with the 7b model.  

My error is about a problem in libllama.so (corrupt?)

**Comment by mayankchhabra** [comment]
@roger- Ah, I see. Would you be able to try a re-build:

```
docker compose build  --no-cache
```

And see if you get any errors during the build. If there are no errors, try running the containers again:

```
docker compose up
```

Feel free to share both `build` and `up` logs if you encounter an error.

**Comment by roger-** [comment]
Thanks, looks like rebuilding as per the latest docker-compose.yaml fixed my problem.

FYI I also added the following to fix a warning and avoid reloading model:

```
    environment:
      ...
      USE_MLOCK: 1
    cap_add:
      - IPC_LOCK
 ```

**Comment by Quarky93** [comment]
Working for me :)

**Comment by miningnome** [comment]
up! just with the

`docker compose up`

my issue has gone ^^

Thank you!
