### ISSUE TITLE
Error starting docker compose: `error loading model: llama.cpp: tensor 'layers.10.ffn_norm.weight' is missing from model`

### ISSUE THREAD

**Issue by jpmcb** [getumbrel/llama-gpt#56]
After running:
```sh
docker compose up
```

I get a strange error in the API - looks like the the something's missing from the model?

```
llama-gpt-llama-gpt-api-7b-1  | /usr/local/lib/python3.11/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
llama-gpt-llama-gpt-api-7b-1  | !!
llama-gpt-llama-gpt-api-7b-1  |
llama-gpt-llama-gpt-api-7b-1  |         ********************************************************************************
llama-gpt-llama-gpt-api-7b-1  |         Please avoid running ``setup.py`` and ``easy_install``.
llama-gpt-llama-gpt-api-7b-1  |         Instead, use pypa/build, pypa/installer or other
llama-gpt-llama-gpt-api-7b-1  |         standards-based tools.
llama-gpt-llama-gpt-api-7b-1  |
llama-gpt-llama-gpt-api-7b-1  |         See https://github.com/pypa/setuptools/issues/917 for details.
llama-gpt-llama-gpt-api-7b-1  |         ********************************************************************************
llama-gpt-llama-gpt-api-7b-1  |
llama-gpt-llama-gpt-api-7b-1  | !!
llama-gpt-llama-gpt-api-7b-1  |   easy_install.initialize_options(self)
llama-gpt-llama-gpt-api-7b-1  | [0/1] Install the project...
llama-gpt-llama-gpt-api-7b-1  | -- Install configuration: "Release"
llama-gpt-llama-gpt-api-7b-1  | -- Up-to-date: /app/_skbuild/linux-aarch64-3.11/cmake-install/llama_cpp/libllama.so
llama-gpt-llama-gpt-api-7b-1  | copying _skbuild/linux-aarch64-3.11/cmake-install/llama_cpp/libllama.so -> llama_cpp/libllama.so
llama-gpt-llama-gpt-api-7b-1  |
llama-gpt-llama-gpt-api-7b-1  | running develop
llama-gpt-llama-gpt-api-7b-1  | /usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
llama-gpt-llama-gpt-api-7b-1  | !!
llama-gpt-llama-gpt-api-7b-1  |
llama-gpt-llama-gpt-api-7b-1  |         ********************************************************************************
llama-gpt-llama-gpt-api-7b-1  |         Please avoid running ``setup.py`` directly.
llama-gpt-llama-gpt-api-7b-1  |         Instead, use pypa/build, pypa/installer or other
llama-gpt-llama-gpt-api-7b-1  |         standards-based tools.
llama-gpt-llama-gpt-api-7b-1  |
llama-gpt-llama-gpt-api-7b-1  |         See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
llama-gpt-llama-gpt-api-7b-1  |         ********************************************************************************
llama-gpt-llama-gpt-api-7b-1  |
llama-gpt-llama-gpt-api-7b-1  | !!
llama-gpt-llama-gpt-api-7b-1  |   self.initialize_options()
llama-gpt-llama-gpt-api-7b-1  | running egg_info
llama-gpt-llama-gpt-api-7b-1  | writing llama_cpp_python.egg-info/PKG-INFO
llama-gpt-llama-gpt-api-7b-1  | writing dependency_links to llama_cpp_python.egg-info/dependency_links.txt
llama-gpt-llama-gpt-api-7b-1  | writing requirements to llama_cpp_python.egg-info/requires.txt
llama-gpt-llama-gpt-api-7b-1  | writing top-level names to llama_cpp_python.egg-info/top_level.txt
llama-gpt-llama-gpt-api-7b-1  | reading manifest file 'llama_cpp_python.egg-info/SOURCES.txt'
llama-gpt-llama-gpt-api-7b-1  | adding license file 'LICENSE.md'
llama-gpt-llama-gpt-api-7b-1  | writing manifest file 'llama_cpp_python.egg-info/SOURCES.txt'
llama-gpt-llama-gpt-api-7b-1  | running build_ext
llama-gpt-llama-gpt-api-7b-1  | Creating /usr/local/lib/python3.11/site-packages/llama-cpp-python.egg-link (link to .)
llama-gpt-llama-gpt-api-7b-1  | llama-cpp-python 0.1.78 is already the active version in easy-install.pth
llama-gpt-llama-gpt-api-7b-1  |
llama-gpt-llama-gpt-api-7b-1  | Installed /app
llama-gpt-llama-gpt-api-7b-1  | Processing dependencies for llama-cpp-python==0.1.78
llama-gpt-llama-gpt-api-7b-1  | Searching for diskcache==5.6.1
llama-gpt-llama-gpt-api-7b-1  | Best match: diskcache 5.6.1
llama-gpt-llama-gpt-api-7b-1  | Processing diskcache-5.6.1-py3.11.egg
llama-gpt-llama-gpt-api-7b-1  | Adding diskcache 5.6.1 to easy-install.pth file
llama-gpt-llama-gpt-api-7b-1  |
llama-gpt-llama-gpt-api-7b-1  | Using /usr/local/lib/python3.11/site-packages/diskcache-5.6.1-py3.11.egg
llama-gpt-llama-gpt-api-7b-1  | Searching for numpy==1.26.0b1
llama-gpt-llama-gpt-api-7b-1  | Best match: numpy 1.26.0b1
llama-gpt-llama-gpt-api-7b-1  | Processing numpy-1.26.0b1-py3.11-linux-aarch64.egg
llama-gpt-llama-gpt-api-7b-1  | Adding numpy 1.26.0b1 to easy-install.pth file
llama-gpt-llama-gpt-api-7b-1  | Installing f2py script to /usr/local/bin
llama-gpt-llama-gpt-api-7b-1  |
llama-gpt-llama-gpt-api-7b-1  | Using /usr/local/lib/python3.11/site-packages/numpy-1.26.0b1-py3.11-linux-aarch64.egg
llama-gpt-llama-gpt-api-7b-1  | Searching for typing-extensions==4.7.1
llama-gpt-llama-gpt-api-7b-1  | Best match: typing-extensions 4.7.1
llama-gpt-llama-gpt-api-7b-1  | Adding typing-extensions 4.7.1 to easy-install.pth file
llama-gpt-llama-gpt-api-7b-1  |
llama-gpt-llama-gpt-api-7b-1  | Using /usr/local/lib/python3.11/site-packages
llama-gpt-llama-gpt-api-7b-1  | Finished processing dependencies for llama-cpp-python==0.1.78
llama-gpt-llama-gpt-api-7b-1  | Initializing server with:
llama-gpt-llama-gpt-api-7b-1  | Batch size: 2096
llama-gpt-llama-gpt-api-7b-1  | Number of CPU threads: 8
llama-gpt-llama-gpt-api-7b-1  | Number of GPU layers: 0
llama-gpt-llama-gpt-api-7b-1  | Context window: 4096
llama-gpt-llama-gpt-api-7b-1  | /usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:127: UserWarning: Field "model_alias" has conflict with protected namespace "model_".
llama-gpt-llama-gpt-api-7b-1  |
llama-gpt-llama-gpt-api-7b-1  | You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ('settings_',)`.
llama-gpt-llama-gpt-api-7b-1  |   warnings.warn(
llama-gpt-llama-gpt-api-7b-1  | llama.cpp: loading model from /models/llama-2-7b-chat.bin
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: format     = ggjt v3 (latest)
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: n_vocab    = 32000
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: n_ctx      = 4096
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: n_embd     = 4096
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: n_mult     = 5504
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: n_head     = 32
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: n_head_kv  = 32
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: n_layer    = 32
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: n_rot      = 128
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: n_gqa      = 1
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: rnorm_eps  = 5.0e-06
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: n_ff       = 11008
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: freq_base  = 10000.0
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: freq_scale = 1
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: model size = 7B
llama-gpt-llama-gpt-api-7b-1  | llama_model_load_internal: ggml ctx size =    0.03 MB
llama-gpt-llama-gpt-api-7b-1  | error loading model: llama.cpp: tensor 'layers.10.ffn_norm.weight' is missing from model
llama-gpt-llama-gpt-api-7b-1  | llama_load_model_from_file: failed to load model
llama-gpt-llama-gpt-api-7b-1  | Traceback (most recent call last):
llama-gpt-llama-gpt-api-7b-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
llama-gpt-llama-gpt-api-7b-1  |   File "<frozen runpy>", line 88, in _run_code
llama-gpt-llama-gpt-api-7b-1  |   File "/app/llama_cpp/server/__main__.py", line 46, in <module>
llama-gpt-llama-gpt-api-7b-1  |     app = create_app(settings=settings)
llama-gpt-llama-gpt-api-7b-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llama-gpt-llama-gpt-api-7b-1  |   File "/app/llama_cpp/server/app.py", line 317, in create_app
llama-gpt-llama-gpt-api-7b-1  |     llama = llama_cpp.Llama(
llama-gpt-llama-gpt-api-7b-1  |             ^^^^^^^^^^^^^^^^
llama-gpt-llama-gpt-api-7b-1  |   File "/app/llama_cpp/llama.py", line 328, in __init__
llama-gpt-llama-gpt-api-7b-1  |     assert self.model is not None
llama-gpt-llama-gpt-api-7b-1  |            ^^^^^^^^^^^^^^^^^^^^^^
llama-gpt-llama-gpt-api-7b-1  | AssertionError
```

### System specs

```
Apple M2 Max
32 GB memory
```

```
❯ docker system info
Client:
 Version:    24.0.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /Users/jpmcb/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /Users/jpmcb/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/jpmcb/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /Users/jpmcb/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /Users/jpmcb/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/jpmcb/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/jpmcb/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     /Users/jpmcb/.docker/cli-plugins/docker-scout

Server:
 Containers: 16
  Running: 1
  Paused: 0
  Stopped: 15
 Images: 34
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 15.61GiB
 Name: docker-desktop
 ID: ea3b77fd-563e-4bef-8f96-aa0f769b3f88
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

```

**Comment by Shahzaib-Hasaan** [comment]
Same Issue😢😢

**Comment by mayankchhabra** [comment]
Sorry folks, this should be fixed in the master now. Please see https://github.com/getumbrel/llama-gpt/issues/68#issuecomment-1694643852 on how to resolve.
